### PR TITLE
Add rate limiting

### PR DESCRIPTION
**Pull request by A2nkF**
Added rate limiting

### CODE REVIEW

**Comment by nomaster** [comment]
Doesn't work properly. This way, the service rings the bell exactly every 10 seconds.

**Comment by msteinhoff** [comment]
> Doesn't work properly. This way, the service rings the bell exactly every 10 seconds.

Besides, the extra thread is not required to achieve the desired functionality.

Simplest possible way I can imagine would be to store the timestamp each time `on_message` is called and only ring bell if `now() - last_call > 10s`.

Or use a [ratelimit library](https://pypi.org/project/ratelimit/), e.g. something like this:

```python
@limits(calls=1, period=10, raise_on_limit=False)
def ring_bell():
    pulse_server.play_sample(args.sample, pulse_sinks[0])

def on_message(mqtt_server, userdata, msg):
    ring_bell()
```

(code not tested)

**Comment by nomaster** [comment]
Thanks @msteinhoff, we did it just the way you described in e7e0eccf9a9a8e75cf1aaaf518408cd09ba60ca4

**Comment by msteinhoff** [comment]
Awesome. You also might want to add a unit test to make sure your code does the things you intended.

Other stuff i noticed:

- ~~The project is missing a [README](https://tom.preston-werner.com/2010/08/23/readme-driven-development.html)~~ Oh there it is. I think it would be great if the README also explains how audio samples are added/changed in pulse audio.

- This project looks very generic (a MQTT-PulseAudio bridge to play a doorbell sound) but also contains infrastructure-specific configuration (default server, default topic, default sound file). I think the CLI should require the user to explicitly configure those settings, and the infrastructure-specific config should be moved to the deployment (e.g. docker-stacks repo).

- The sink is hard-coded to `pulse_sinks[0]`. Is this always the right sink? Might there be more than one sink? Does it make sense to make this a configurable option?

- Inconsistent ways of configuration: pulse audio server is configured via environment variable, everything else via arguments. I think it would be better if everything is configured consistently, e.g. if there is a way to configure the pulse audio server via argument, too.

- You might want to use the python logging library instead of print() statements

Should I create some more issues for this?

**Comment by nomaster** [comment]
Yes, all good points that we of course had in mind. 😁 

Please feel free to write issues for these points! Code contributions are welcome, as well.

**Pull request closed without merging**
